model: opt-125m
stage_args:
  - stage_id: 0
    stage_type: llm
    model: /root/.cache/huggingface/hub/models--facebook--opt-125m/
    runtime:
      devices: cpu
      max_batch_size: 1
    engine_args:
      trust_remote_code: true
final_output: true
final_output_type: text